export const HUB_CHANNELS = {
	register: "hub:register",
	unregister: "hub:unregister",
	ask: "hub:ask",
	request: "hub:request",
	reply: "hub:reply",
	answer: "hub:answer",
} as const;

/**
 * Explicit user-wait protocol. The extension that opens the UI declares a wait
 * with `set` and clears it with `clear`; hub stores the declarations and emits
 * the aggregate on `changed`. Pending `hub:ask` requests are never inferred as
 * waits. `ack` lets a client detect synchronously whether this hub supports the
 * protocol (pi event dispatch is synchronous).
 */
export const HUB_USER_WAIT_CHANNELS = {
	set: "hub:user-wait:set",
	clear: "hub:user-wait:clear",
	changed: "hub:user-wait:changed",
	ack: "hub:user-wait:ack",
} as const;

/**
 * External Herdr compatibility event. Herdr's managed Pi integration counts
 * `active: true` / `active: false` to derive its own blocked state, so hub must
 * emit exactly one enter when the aggregate leaves zero and one exit when the
 * last wait clears.
 */
export const HERDR_BLOCKED_EVENT = "herdr:blocked";

// The registry module owns the wait payload/snapshot shapes; re-export them so
// protocol consumers have a single import surface.
export type {
	UserWaitClearPayload,
	UserWaitEntry,
	UserWaitKind,
	UserWaitSetPayload,
	UserWaitSnapshot,
} from "./user-wait";

/** Registry operation acknowledged on `HUB_USER_WAIT_CHANNELS.ack`. */
export type UserWaitOperation = "set" | "clear";

/** Acknowledgement that hub accepted a `set` or `clear` declaration. */
export type HubUserWaitAckPayload = {
	id: string;
	owner: string;
	operation: UserWaitOperation;
};

/**
 * Semantic progress reporting protocol. This is an observer protocol, not a
 * capability: it is deliberately absent from `HUB_CHANNELS.register` and from
 * permission arbitration. Producers mutate a hub-owned registry over
 * `create`/`update`/`finish`/`remove`; observers receive detached aggregate
 * snapshots on `changed` and correlated replies on `snapshot`.
 */
export const HUB_PROGRESS_CHANNELS = {
	create: "hub:progress:create",
	update: "hub:progress:update",
	finish: "hub:progress:finish",
	remove: "hub:progress:remove",
	changed: "hub:progress:changed",
	ack: "hub:progress:ack",
	query: "hub:progress:query",
	snapshot: "hub:progress:snapshot",
} as const;

/** Lifecycle state of a single chunk. `reviewing` is a phase, not a state. */
export const PROGRESS_CHUNK_STATES = [
	"pending",
	"active",
	"blocked",
	"done",
	"failed",
	"skipped",
] as const;

export type ProgressChunkState = (typeof PROGRESS_CHUNK_STATES)[number];

/** Terminal outcome of a whole tracker. Absent means the tracker is active. */
export const PROGRESS_OUTCOMES = ["completed", "failed", "cancelled"] as const;

export type ProgressOutcome = (typeof PROGRESS_OUTCOMES)[number];

/** One node supplied at create time. `id` is unique within the tracker. */
export interface ProgressChunkDefinition {
	id: string;
	label?: string;
	/** Earlier node whose direct child this is. Omission makes this a root node. */
	parentId?: string;
	/** Singular display noun for this node's direct children. */
	childUnit?: string;
}

export interface ProgressPathSegment {
	index: number;
	total: number;
	unit: string;
	label?: string;
}

/** Lightweight leaf observer shape. */
export interface ProgressChunkSnapshot {
	/** One-based index in the immutable leaf projection. */
	index: number;
	state: ProgressChunkState;
	label?: string;
	/** Root-to-leaf location, emitted only for hierarchical trackers. */
	path?: ProgressPathSegment[];
	phase?: string;
}

/** Lightweight per-tracker observer shape. */
export interface ProgressTrackerSnapshot {
	trackerId: string;
	owner: string;
	title: string;
	/** Singular display noun, for example "Stage" or "File". */
	unit: string;
	chunks: ProgressChunkSnapshot[];
	updatedAt: number;
}

/**
 * Aggregate observer snapshot. Deliberately contains active (unfinished)
 * trackers only; full records and history stay inside the registry.
 */
export interface ProgressSnapshot {
	/** True exactly when `count > 0`. */
	active: boolean;
	/** Number of unfinished trackers; always equals `trackers.length`. */
	count: number;
	/** Unfinished trackers only. */
	trackers: ProgressTrackerSnapshot[];
}

export interface ProgressCreatePayload {
	requestId: string;
	trackerId: string;
	/** Opaque identity token generated by the producer for this incarnation. */
	trackerToken: string;
	owner: string;
	title: string;
	unit?: string;
	chunks: ProgressChunkDefinition[];
}

export interface ProgressUpdatePayload {
	requestId: string;
	trackerId: string;
	trackerToken: string;
	owner: string;
	chunkId: string;
	state: ProgressChunkState;
	/** Omission clears the previous phase. */
	phase?: string;
	/** Omission clears the previous detail. */
	detail?: string;
}

export interface ProgressFinishPayload {
	requestId: string;
	trackerId: string;
	trackerToken: string;
	owner: string;
	outcome: ProgressOutcome;
	summary?: string;
}

export interface ProgressRemovePayload {
	requestId: string;
	trackerId: string;
	trackerToken: string;
	owner: string;
}

/** Registry operation acknowledged on `HUB_PROGRESS_CHANNELS.ack`. */
export type ProgressOperation = "create" | "update" | "finish" | "remove";

export type ProgressAckError =
	| "already-exists"
	| "not-found"
	| "limit-exceeded"
	| "stale-tracker"
	| "tracker-finished"
	| "not-leaf"
	| "chunk-terminal"
	| "invalid-transition"
	| "incomplete"
	| "conflict";

/**
 * Correlated acknowledgement for a syntactically valid mutation. Malformed
 * payloads are ignored and receive no acknowledgement. `changed` describes a
 * mutation of the full registry record/history, so accepted idempotent
 * operations return `ok: true, changed: false`. Emitted before `changed`.
 */
export interface HubProgressAckPayload {
	requestId: string;
	trackerId: string;
	trackerToken: string;
	owner: string;
	operation: ProgressOperation;
	ok: boolean;
	changed: boolean;
	error?: ProgressAckError;
}

/** Observer request for the current aggregate snapshot. */
export interface ProgressQueryPayload {
	requestId: string;
}

/** Correlated response on `HUB_PROGRESS_CHANNELS.snapshot`. */
export interface HubProgressSnapshotPayload {
	requestId: string;
	snapshot: ProgressSnapshot;
}

export const HUB_PERMISSIONS = {
	shell: "perm:shell",
	io: "perm:io",
	net: "perm:net",
	agent: "perm:agent",
} as const;

export type PermissionAction = "allow" | "confirm" | "block";

export type CapRequest = {
	what: string;
	data: Record<string, unknown>;
};

export type CapResult = {
	what: string;
	action: PermissionAction;
	reason?: string;
	// Optional human-readable one-line description of the classified call.
	// Requesters (e.g. safe-mode) may use it for approval prompts.
	summary?: string;
};

export type HubRegisterPayload = {
	id: string;
	caps: { provide: string[] };
};

export type HubUnregisterPayload = {
	id: string;
};

export type HubAskPayload = {
	id: string;
	from?: string;
	ctx?: unknown;
	cap: CapRequest[];
};

export type HubRequestPayload = HubAskPayload & {
	targets: string[];
};

export type HubReplyPayload = {
	id: string;
	from?: string;
	results: CapResult[];
};

export type HubAnswerPayload = {
	id: string;
	results: CapResult[];
};
