/** Short startup mottos. Keep these compact enough to sit beside /ᴘx▌. */
export const STARTUP_MOTTOS = [
	"stay in flow",
	"make room for the next idea",
	"small steps, sharp tools",
	"turn curiosity into code",
	"less noise, more signal",
	"build at the speed of thought",
	"one good change at a time",
	"keep the loop short",
	"find the simple path",
	"think clearly, build gently",
	"your next idea starts here",
	"let the terminal breathe",
	"focus is a superpower",
	"follow the useful question",
	"make the next step obvious",
	"a quiet place to build",
	"keep what matters close",
	"start small, go deep",
	"clarity before cleverness",
	"leave space for discovery",
	"neon dreams, working code",
	"ride the synthwave",
	"follow the glowing cursor",
	"bright pixels, clear intent",
	"a little neon, a lot of focus",
	"tune into the signal",
	"build beyond the static",
	"midnight ideas welcome",
	"keep your future editable",
	"light up the next line",
	"cyberpunk outside, calm inside",
	"the console is your cockpit",
	"find your frequency",
	"dream in pixels, ship in steps",
	"a softer glow, a sharper edge",
	"cross the noise floor",
	"the cursor is your compass",
	"keep the night productive",
	"bright ideas need no spotlight",
	"next stop: something useful",
	"ask first, guess less",
	"read the code, then the room",
	"measure twice, patch once",
	"make bugs tell their story",
	"test the edge, trust the evidence",
	"let the tests do the talking",
	"simple code ages well",
	"understand before you optimize",
	"make it work, make it clear",
	"leave the code kinder",
	"a good name saves a paragraph",
	"trace the cause, not the blame",
	"keep the diff worth reading",
	"fix the root, not the shadow",
	"small commits, steady progress",
	"make failure informative",
	"check assumptions at the door",
	"the happy path needs neighbors",
	"refactor with a reason",
	"correctness has good taste",
	"make something worth keeping",
	"ideas deserve a first draft",
	"prototype the possibility",
	"try the smaller experiment",
	"give the weird idea a chance",
	"build a bridge to what if",
	"a blank line is an invitation",
	"start where your curiosity points",
	"rough drafts move things forward",
	"make the invisible tangible",
	"sketch first, polish later",
	"create a little more possibility",
	"let the question lead",
	"explore without the hurry",
	"turn maybe into a prototype",
	"bring your unfinished ideas",
	"find delight in the details",
	"a tiny tool can open a big door",
	"build the thing you wish existed",
	"useful can be beautiful",
	"progress, not performance",
	"one task, one clear next step",
	"take the pressure off the prompt",
	"you can begin before you know",
	"slow is smooth, smooth is fast",
	"rest is part of the process",
	"keep your pace human",
	"the next step is enough",
	"a little progress still counts",
	"pause, notice, continue",
	"you do not need every answer",
	"make space for a better question",
	"finish a thought, not a marathon",
	"today can start with one line",
	"work with your attention",
	"breathe between the builds",
	"gentle focus goes a long way",
	"there is room to change your mind",
	"momentum starts smaller than you think",
	"let good enough unlock the next step",
	"hello, possibility",
	"ready when you are",
	"less ceremony, more making",
	"your shell, your rhythm",
	"a pocket-sized launchpad",
	"put the tools to work",
	"the terminal has good company",
	"keep your hands near the ideas",
	"from prompt to possibility",
	"a tiny cursor, a wide horizon",
	"think outside the text box",
	"every session is a fresh canvas",
	"bring intent, leave with a diff",
	"make the useful thing easy",
	"keep the magic inspectable",
	"good tools get out of the way",
	"a shortcut to your next question",
	"more room for the interesting bits",
	"build with the lights on",
	"onward, one line at a time",
] as const;

/** Called once per session start, not on component redraw. */
export function pickStartupMotto(): string {
	return STARTUP_MOTTOS[Math.floor(Math.random() * STARTUP_MOTTOS.length)] ?? STARTUP_MOTTOS[0];
}
